# AI API Configuration
ai.api.key=AIzaSyBb5-018GF0Uunl0ZadZmtG-gTXCOrB_fw
ai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
ai.api.model=gemini-1.5-flash